name: tealeaves
description: TeaLeaves
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  stacked_shared: any
  google_fonts: ^6.2.1
  firebase_core: ^2.24.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/images/branding/logo.png

flutter_gen:
