// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2HHF5uarMmbQ2tmZU9zG5t3HHp9bfx38',
    appId: '1:237230438068:web:fd2090e18583d12afb89e1',
    messagingSenderId: '237230438068',
    projectId: 'tealeaves-90703',
    authDomain: 'tealeaves-90703.firebaseapp.com',
    storageBucket: 'tealeaves-90703.appspot.com',
    measurementId: 'G-C4MSS0E38H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt-FoSP7i8sg6tgqz15al98dk3JiCscKw',
    appId: '1:237230438068:android:dba01285192be1defb89e1',
    messagingSenderId: '237230438068',
    projectId: 'tealeaves-90703',
    storageBucket: 'tealeaves-90703.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKK1KiCVV_MG1N3xDjEE3vWpV5a--ZG2U',
    appId: '1:237230438068:ios:ba9252d862d7ee38fb89e1',
    messagingSenderId: '237230438068',
    projectId: 'tealeaves-90703',
    storageBucket: 'tealeaves-90703.appspot.com',
    iosBundleId: 'ca.tibbs.tealeaves',
  );
}
